### ISSUE TITLE
Add support for 16.x and 14.x

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs-dependency-vuln-assessments#58]

**Comment by mhdawson** [comment]
@facutuesca I know you were working on updates to the scripts in support of adding other streams.  

I'm wondering if there is any progress to report?

**Comment by facutuesca** [comment]
@mhdawson 
Yes, sorry for the delay. PR open [here](https://github.com/nodejs/nodejs-dependency-vuln-assessments/pull/59)
